"""
gRPC servicer for Optimize: reads Neo4j knowledge graph, yields streamed progress, caches plan in Redis.
"""
from __future__ import annotations

import asyncio
import time
from typing import Generator

from ai_core.neo4j_schema import get_driver
from ai_core import cache

# Generated by protoc in Docker (or run scripts/generate_proto.py)
try:
    from ai_core import optimize_pb2 as pb
    from ai_core import optimize_pb2_grpc as pb_grpc
except ImportError:
    pb = None
    pb_grpc = None


STATUSES = [
    ("FETCHING_DATA", 15, "Loading portfolio and knowledge graph"),
    ("COMPUTING_GRAPH", 40, "Computing opportunity subgraph"),
    ("GENERATING_PLAN", 70, "Generating optimization plan"),
    ("WAITING_FOR_SIGNATURE", 85, "Ready for your approval"),
    ("DONE", 100, "Optimization complete"),
]


def _yield_progress(
    optimization_id: str,
    request_wallet: str,
):
    if pb is None or pb_grpc is None:
        return
    for status, progress, summary in STATUSES:
        msg = pb.OptimizeProgress(
            optimization_id=optimization_id,
            status=status,
            progress=progress,
            summary=summary,
        )
        yield msg
        time.sleep(0.4)
    # Build plan from Neo4j
    driver = get_driver()
    actions = []
    expected_apy = 0.0
    risk_score = 0.0
    explanation = ""
    try:
        with driver.session() as session:
            result = session.run("""
                MATCH (o:Opportunity)-[:DENOMINATED_IN]->(a:Asset)
                WHERE o.apy > 0
                RETURN o.id AS id, o.apy AS apy, o.riskScore AS risk, a.symbol AS symbol
                ORDER BY o.apy DESC
                LIMIT 5
            """)
            for record in result:
                actions.append(pb.RecommendedAction(
                    id=record["id"],
                    type="DEPOSIT",
                    chain_id="ethereum",
                    protocol_id="aave-v3-ethereum",
                    asset_id=record.get("symbol", "USDT"),
                    amount="0",
                    amount_usd="0",
                    reason=f"APY {record['apy']}%, risk {record['risk']}",
                ))
                if record["apy"]:
                    expected_apy = max(expected_apy, float(record["apy"]))
                if record["risk"] is not None:
                    risk_score = max(risk_score, float(record["risk"]))
            explanation = "Top opportunities from knowledge graph (Neo4j)."
    finally:
        driver.close()
    plan = pb.OptimizationPlan(
        actions=actions,
        expected_yield_apy=expected_apy,
        risk_score=risk_score,
        explanation=explanation or "Based on current graph state.",
    )
    # Cache plan for execute step
    cache.cache_set(
        cache.optimization_plan_key(optimization_id),
        {
            "actions": [{"id": a.id, "type": a.type, "chain_id": a.chain_id, "protocol_id": a.protocol_id, "asset_id": a.asset_id, "reason": a.reason} for a in actions],
            "expected_yield_apy": expected_apy,
            "risk_score": risk_score,
            "explanation": explanation,
        },
        ttl_sec=cache.PLAN_TTL,
    )
    yield pb.OptimizeProgress(
        optimization_id=optimization_id,
        status="DONE",
        progress=100,
        summary="Plan ready",
        partial_plan=plan,
    )


_servicer_instance = None

def _get_servicer():
    global _servicer_instance
    if pb_grpc is None:
        return None
    if _servicer_instance is None:
        class _OptimizerServicer(pb_grpc.OptimizerServicer):
            def Optimize(self, request, context):
                optimization_id = request.optimization_id or "unknown"
                wallet = request.wallet_address or ""
                return _yield_progress(optimization_id, wallet)
        _servicer_instance = _OptimizerServicer()
    return _servicer_instance

def add_servicer_to_server(server):
    s = _get_servicer()
    if s is not None and pb_grpc is not None:
        pb_grpc.add_OptimizerServicer_to_server(s, server)
