# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: optimize.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'optimize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eoptimize.proto\x12\nyieldagent\"|\n\x0fOptimizeRequest\x12\x16\n\x0ewallet_address\x18\x01 \x01(\t\x12\x17\n\x0foptimization_id\x18\x02 \x01(\t\x12\x38\n\x0b\x63onstraints\x18\x03 \x01(\x0b\x32#.yieldagent.OptimizationConstraints\"b\n\x17OptimizationConstraints\x12\x16\n\x0erisk_tolerance\x18\x01 \x01(\t\x12\x15\n\rtarget_chains\x18\x02 \x03(\t\x12\x18\n\x10max_gas_cost_usd\x18\x03 \x01(\x01\"\xa1\x01\n\x10OptimizeProgress\x12\x17\n\x0foptimization_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x05\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\x12\x32\n\x0cpartial_plan\x18\x06 \x01(\x0b\x32\x1c.yieldagent.OptimizationPlan\"\x87\x01\n\x10OptimizationPlan\x12.\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x1d.yieldagent.RecommendedAction\x12\x1a\n\x12\x65xpected_yield_apy\x18\x02 \x01(\x01\x12\x12\n\nrisk_score\x18\x03 \x01(\x01\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t\"\x9a\x01\n\x11RecommendedAction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\t\x12\x13\n\x0bprotocol_id\x18\x04 \x01(\t\x12\x10\n\x08\x61sset_id\x18\x05 \x01(\t\x12\x0e\n\x06\x61mount\x18\x06 \x01(\t\x12\x12\n\namount_usd\x18\x07 \x01(\t\x12\x0e\n\x06reason\x18\x08 \x01(\t2T\n\tOptimizer\x12G\n\x08Optimize\x12\x1b.yieldagent.OptimizeRequest\x1a\x1c.yieldagent.OptimizeProgress0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'optimize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPTIMIZEREQUEST']._serialized_start=30
  _globals['_OPTIMIZEREQUEST']._serialized_end=154
  _globals['_OPTIMIZATIONCONSTRAINTS']._serialized_start=156
  _globals['_OPTIMIZATIONCONSTRAINTS']._serialized_end=254
  _globals['_OPTIMIZEPROGRESS']._serialized_start=257
  _globals['_OPTIMIZEPROGRESS']._serialized_end=418
  _globals['_OPTIMIZATIONPLAN']._serialized_start=421
  _globals['_OPTIMIZATIONPLAN']._serialized_end=556
  _globals['_RECOMMENDEDACTION']._serialized_start=559
  _globals['_RECOMMENDEDACTION']._serialized_end=713
  _globals['_OPTIMIZER']._serialized_start=715
  _globals['_OPTIMIZER']._serialized_end=799
# @@protoc_insertion_point(module_scope)
