// API Configuration - Modular backend connection
export const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_URL || 'http://localhost:8000',
  ENDPOINTS: {
    HEALTH: '/health',
    PRICE_CALL_BS: '/price/call/bs',
    PRICE_PUT_BS: '/price/put/bs',
    PRICE_CALL_FFT: '/price/call/fft',
    PRICE_PUT_FFT: '/price/put/fft',
    PRICE_CALL_FFT_OPT: '/price/call/fft-optimized',
    PRICE_PUT_FFT_OPT: '/price/put/fft-optimized',
    PRICE_CALL_HESTON: '/price/call/heston',
    PRICE_PUT_HESTON: '/price/put/heston',
    GREEKS_CALL: '/greeks/call',
    GREEKS_PUT: '/greeks/put',
    // Market Data endpoints
    MARKET_DATA_HEALTH: '/market-data/health',
    MARKET_DATA_SPOT: '/market-data/spot',
    MARKET_DATA_OPTION_CHAIN: '/market-data/option-chain',
    MARKET_DATA_SYMBOLS: '/market-data/symbols',
    MARKET_DATA_CACHE_STATS: '/market-data/cache/stats',
    MARKET_DATA_CACHE_CLEAR: '/market-data/cache/clear',
    // Transact Phase 1
    PORTFOLIO_MOMENTS: '/portfolio/moments',
    PORTFOLIO_PERFORMANCE: '/portfolio/performance',
    RISK_VAR: '/risk/var',
    RISK_ES: '/risk/es',
    OPTIMIZE_MVO: '/optimize/mvo',
    OPTIMIZE_MVO_FRONTIER: '/optimize/mvo/frontier',
    BLOTTER_CHART_BARS: '/blotter/chart/bars',
    BLOTTER_INSTRUMENTS: '/blotter/instruments',
    BLOTTER_TRADE: '/blotter/trade',
    BLOTTER_POSITIONS: '/blotter/positions',
    BLOTTER_HISTORY: '/blotter/history',
    // Transact Phase 2
    OPTIMIZE_BLM: '/optimize/blm',
    OPTIMIZE_RISK_PARITY: '/optimize/risk-parity',
    OPTIMIZE_HRP: '/optimize/hrp',
    OPTIMIZE_KELLY: '/optimize/kelly',
    OPTIMIZE_KELLY_SINGLE: '/optimize/kelly/single',
    // Phase 3
    FACTORS_ESTIMATE: '/factors/estimate',
    FACTORS_FAMA_MACBETH: '/factors/fama-macbeth',
    PORTFOLIO_COSKEWNESS: '/portfolio/coskewness',
    PORTFOLIO_ATTRIBUTION: '/portfolio/attribution',
    RISK_COVARIANCE_HEALTH: '/risk/covariance-health',
    RISK_MST: '/risk/mst',
    RISK_GREEKS_AGGREGATE: '/risk/greeks-aggregate',
    HESTON_CALIBRATE: '/heston/calibrate',
    VOL_IMPLIED_SURFACE: '/vol/implied-surface',
    VOL_HESTON_SURFACE: '/vol/heston-surface',
    VOL_HISTORICAL: '/vol/historical',
    VOL_FACTOR_DECOMPOSE: '/vol/factor-decompose',
    FACTORS_SMART_BETA: '/factors/smart-beta',
    FACTORS_CROWDING: '/factors/crowding',
    FACTORS_PCA: '/factors/pca',
    // Phase 4: Scenarios & Behavioral
    SCENARIOS_DEFINE: '/scenarios/define',
    SCENARIOS_RUN: '/scenarios/run',
    SCENARIOS_PROBABILISTIC: '/scenarios/probabilistic',
    SCENARIOS_MONTE_CARLO: '/scenarios/monte-carlo',
    SCENARIOS_BEHAVIORAL: '/scenarios/behavioral',
    BLOTTER_ATTRIBUTION: '/blotter/attribution',
    BLOTTER_PNL: '/blotter/pnl',
    // Asset Universe (yfinance)
    ASSETS_TYPES: '/assets/types',
    ASSETS_SEARCH: '/assets/search',
    ASSETS_HISTORY: '/assets/history',
    ASSETS_QUOTE: '/assets/quote',
    ASSETS_OPTIONS: '/assets/options',
    ASSETS_PROVIDERS: '/assets/providers',
    ASSETS_MOVERS: '/assets/movers',
  },
  TIMEOUT: 30000,
} as const;

export const DEMO_CONFIG = {
  REFRESH_INTERVAL: 5000, // 5 seconds
  SAMPLE_CALCULATIONS: 1000,
  PERFORMANCE_METRICS: {
    BS_AVG_TIME: 2,
    MC_AVG_TIME: 45,
    FFT_AVG_TIME: 15,
  },
} as const;
