/**
 * EconomyContext — Tracks real-time economic telemetry for the Agentic Economy on Arc.
 * 
 * Captures:
 *  - On-chain transactions generated by agents/users.
 *  - Total USDC throughput.
 *  - Gas savings calculated via MarginAnalyzer (Arc vs ETH).
 *  - Agent reputations (ERC-8004 sync).
 */
import {
  createContext,
  useContext,
  useState,
  useCallback,
  useEffect,
  type ReactNode,
} from 'react';

export interface OnChainTx {
  id: string;
  hash: string;
  method: string;
  price: number;
  from: string;
  to: string;
  timestamp: number;
  sponsored: boolean;
}

export interface AgentReputation {
  did: string;
  name: string;
  score: number;
  accuracy: number;
  uptime: number;
  citations: number;
}

interface EconomyContextValue {
  transactions: OnChainTx[];
  addTransaction: (tx: Partial<OnChainTx>) => void;
  totalThroughput: number;
  totalSavings: number;
  agentReputations: AgentReputation[];
  refreshReputations: () => Promise<void>;
  isGasSponsored: boolean;
}

const EconomyCtx = createContext<EconomyContextValue>({
  transactions: [],
  addTransaction: () => {},
  totalThroughput: 0,
  totalSavings: 0,
  agentReputations: [],
  refreshReputations: async () => {},
  isGasSponsored: true,
});

const ETH_GAS_ESTIMATE = 0.50;
const ARC_GAS_ESTIMATE = 0.0001;

export function EconomyContextProvider({ children }: { children: ReactNode }) {
  const [transactions, setTransactions] = useState<OnChainTx[]>([]);
  const [agentReputations, setReputations] = useState<AgentReputation[]>([]);
  const [isGasSponsored] = useState(true);

  const addTransaction = useCallback((partialTx: Partial<OnChainTx>) => {
    const fullTx: OnChainTx = {
      id: partialTx.id || Math.random().toString(36).substring(7),
      hash: partialTx.hash || '0x...',
      method: partialTx.method || 'Unknown',
      price: partialTx.price || 0,
      from: partialTx.from || 'User',
      to: partialTx.to || 'Agent',
      timestamp: Date.now(),
      sponsored: true,
    };
    setTransactions(prev => [fullTx, ...prev].slice(0, 50));
  }, []);

  const totalThroughput = transactions.reduce((sum, tx) => sum + tx.price, 0);
  const totalSavings = transactions.length * (ETH_GAS_ESTIMATE - ARC_GAS_ESTIMATE);

  const refreshReputations = useCallback(async () => {
    try {
      // In production, this would fetch from Neo4j or the Arc Chain indexer
      // For the demo, we simulate a slight increase based on activity
      const mockReputations: AgentReputation[] = [
        { 
          did: 'did:arc:agent_quant_nova', 
          name: 'Manager Agent', 
          score: 0.88, 
          accuracy: 0.85, 
          uptime: 0.99, 
          citations: 120500 
        },
        { 
          did: 'did:arc:agent_research_specialist', 
          name: 'Curator Agent', 
          score: 0.94, 
          accuracy: 0.92, 
          uptime: 0.995, 
          citations: 120550 
        }
      ];
      setReputations(mockReputations);
    } catch (err) {
      console.error('Failed to refresh reputations', err);
    }
  }, []);

  useEffect(() => {
    refreshReputations();
  }, [refreshReputations]);

  return (
    <EconomyCtx.Provider value={{
      transactions,
      addTransaction,
      totalThroughput,
      totalSavings,
      agentReputations,
      refreshReputations,
      isGasSponsored,
    }}>
      {children}
    </EconomyCtx.Provider>
  );
}

export function useEconomyContext() {
  return useContext(EconomyCtx);
}
