name,definition,category,difficulty,menu_context,prerequisites
Scenario Analysis,Evaluating portfolio under hypothetical market scenarios. E[ΔP|scenario] = wᵀ·E[Δr|scenario].,risk_management,intermediate,Scenarios,"what-if analysis;sensitivity;shock propagation;stress testing"
Stress Testing,Evaluating portfolio under extreme scenarios (historical crises or hypothetical shocks beyond normal experience).,risk_management,intermediate,Scenarios,"tail risk;crisis scenarios;regulatory requirements;CCAR"
Historical Scenario,Using actual historical periods as scenarios (2008 crisis, 2020 pandemic, etc.).,risk_management,basic,Scenarios,"historical simulation;crisis periods;drawdown analysis;precedent"
Hypothetical Scenario,Constructed scenario based on assumed market moves (e.g., +200bps rates, -30% equity).,risk_management,intermediate,Scenarios,"shock design;correlation assumptions;second-order effects"
Monte Carlo Scenarios,Generating thousands of random return paths from fitted distribution for scenario analysis.,risk_management,advanced,Scenarios,"simulation;path generation;distribution fitting;confidence intervals"
Sensitivity Analysis,Measuring portfolio sensitivity to individual risk factors. ΔP ≈ Σ(∂P/∂r_i)·Δr_i.,risk_management,basic,Scenarios,"Greeks;duration/convexity;factor exposure;partial derivatives"
What-If Analysis,Exploring portfolio outcomes under assumed conditions. "What if rates rise 100bps?",risk_management,basic,Scenarios,"scenario design;assumption tracking;impact assessment"
Reverse Stress Testing,Identifying scenarios that would cause portfolio failure. "What would break this portfolio?",risk_management,advanced,Scenarios,"failure modes;tail risk;risk identification"
Contagion Analysis,Modeling how shocks propagate through correlated assets/markets.,risk_management,advanced,Scenarios,"correlation breakdown;systemic risk;network effects"
Liquidity Scenario,Scenario assessing impact of liquidity drought (bid-ask widening, volume collapse).,liquidity_risk,advanced,Scenarios,"market liquidity;funding liquidity;fire sales"
Funding Scenario,Scenario assessing impact of funding stress (margin calls, repo haircuts).,liquidity_risk,advanced,Scenarios,"funding liquidity;leverage;margin requirements"
Correlation Scenario,Scenario where correlations change (typically increase in crises).,risk_management,intermediate,Scenarios,"correlation breakdown;diversification failure;contagion"
Volatility Scenario,Scenario where volatility spikes (VIX doubles, triples, etc.).,risk_management,intermediate,Scenarios,"volatility shock;variance risk;option portfolios"
Rate Shock Scenario,Scenario with sudden interest rate change (+/- 100, 200, 300 bps).,interest_rate_risk,basic,Scenarios,"duration;convexity;yield curve;fixed income"
Yield Curve Scenario,Scenario with yield curve shift (parallel, steepening, flattening, twist).,interest_rate_risk,intermediate,Scenarios,"key rate duration;curve factors;PC analysis"
Credit Spread Scenario,Scenario where credit spreads widen/narrow. Impacts corporate bonds, CDS.,credit_risk,intermediate,Scenarios,"spread duration;credit risk;default probability"
FX Shock Scenario,Scenario with currency devaluation/appreciation. Impacts unhedged foreign assets.,currency_risk,intermediate,Scenarios,"currency exposure;FX hedging;translation risk"
Commodity Shock Scenario,Scenario with commodity price spike/collapse. Energy, metals, agriculture.,commodity_risk,intermediate,Scenarios,"commodity exposure;inflation hedge;supply-demand"
Geopolitical Scenario,Scenario based on geopolitical events (war, trade war, sanctions, elections).,event_risk,intermediate,Scenarios,"political risk;sovereign risk;regime change"
Regulatory Scenario,Scenario assessing impact of regulatory changes (capital requirements, taxes).,regulatory_risk,intermediate,Scenarios,"Basel III;Solvency II;tax policy;compliance"
Climate Scenario,Scenario assessing climate-related risks (physical risk, transition risk).,esg_risk,advanced,Scenarios,"TCFD;carbon pricing;stranded assets;physical damage"
Transition Risk,Risk from transition to low-carbon economy (carbon tax, technology change).,esg_risk,advanced,Scenarios,"carbon pricing;policy risk;technology disruption"
Physical Risk,Risk from climate-related physical events (floods, fires, storms).,esg_risk,advanced,Scenarios,"catastrophe modeling;insurance;adaptation"
Probability Weighting,Assigning probabilities to scenarios. Equal, subjective, or model-implied.,decision_theory,intermediate,Scenarios,"probability assessment;Bayesian updating;ambiguity"
Scenario Probability,Subjective or model-implied likelihood of scenario occurring. Σp_s = 1.,risk_management,intermediate,Scenarios,"probability distribution;subjective assessment;calibration"
Expected Shortfall (Scenario),ES = Σ_s p_s · Loss_s. Weighted average loss across scenarios.,risk_metrics,intermediate,Scenarios,"scenario weighting;tail risk;coherent measure"
Worst-Case Scenario,Scenario with maximum loss. Min_{s} P_s. Used for conservative risk assessment.,risk_management,basic,Scenarios,"maximin;robust optimization;pessimistic"
Best-Case Scenario,Scenario with maximum gain. Max_{s} P_s. Used for upside potential assessment.,risk_management,basic,Scenarios,"optimistic;upside potential;aspiration level"
Base Case Scenario,Most likely scenario (highest probability). Benchmark for comparison.,risk_management,basic,Scenarios,"central tendency;mode;reference scenario"
Scenario Weighting,Assigning importance weights to scenarios for aggregation. w_s ∝ p_s or subjective.,decision_theory,intermediate,Scenarios,"probability;subjective weights;robustness"
Regime Switching,Model where parameters change based on latent state. Markov-switching models.,econometrics,advanced,Scenarios,"hidden Markov model;state estimation;parameter instability"
Early Warning Signals,Indicators that precede stress scenarios (volatility spike, correlation increase).,risk_management,advanced,Scenarios,"leading indicators;predictive signals;threshold triggers"
